name: Label PRs

on:
  workflow_call:

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Add labels
    steps:
      - uses: srvaroa/labeler@v1.10.1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
